# Problem 1

$$
P(B|A) = \frac{p(A\ and\ B)}{P(A)}
$$
$$p(A|B) = \frac{P(A) \times P(B|A) }{P(B)} $$

In [1]:
from sklearn.naive_bayes import GaussianNB
import numpy as np

In [ ]:
x1 = [0, 0, 0, 0, 1, 1, 1, 1]
x2 = [0, 0, 1, 1, 0, 0, 1, 1]
y = [1, 1, 1, 1, 0, 0, 1, 0]

In [ ]:
X = np.column_stack((x1, x2))
X

array([[0, 0],
       [0, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1]])

In [ ]:
gnb = GaussianNB()
gnb.fit(X, y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
gnb.get_params()

{'priors': None, 'var_smoothing': 1e-09}

In [ ]:
(4/5) * (2/5)

0.32000000000000006

# Problem 2

In [7]:
w1 = np.array([[1, -1], [-1, 1]])
w2 = np.array([[-1, -1], [1, 1]])
w3 = np.array([[1], [1]])
x = np.array([1, 2])

In [27]:
import math
from numpy import tanh

def tanh_derivative(x):
    t=(np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
    dt=1-t**2
    return dt

def sigmoid(X):
   return 1/(1+np.exp(-X))


def sigmoid_derivative(x):
    outcome = sigmoid(x)
    return outcome * (1 - outcome)


In [15]:
layer1 = x.dot(w1)
layer1 = tanh(layer1)
layer1

array([-0.76159416,  0.76159416])

In [19]:
layer2 = layer1.dot(w2)
print(layer2)
layer2 = tanh(layer2)
layer2

[1.52318831 1.52318831]


array([0.90925167, 0.90925167])

In [22]:
output = layer2.dot(w3)
output *2

array([3.6370067])

In [23]:
e = sigmoid(output) 
e

array([0.86038644])

backprop

$$error_{hidden} = w^T * error_{output}$$

In [41]:
b_layer2 = e * tanh_derivative(layer2)
b_layer2

array([0.41340402, 0.41340402])

In [55]:
b_layer1_err = b_layer2.dot(w2.T)
b_layer1 = b_layer1_err * tanh_derivative(layer1)
b_layer1

array([-0.48601162,  0.48601162])

In [50]:
x[1] * b_layer1[0]

0.0

In [51]:
0.76 * b_layer2[1]

0.31418705778577294

In [52]:
w = np.array([[0.1, 0.5], [-0.3, 0.8]])
x = np.array([[0.2], [0.4]])

In [53]:
w.dot(x).dot(2)

array([[0.44],
       [0.52]])

# Feedforward Neural Network

In [1]:
def relu(n):
    if n<0:
        return 0
    else:
        return n

In [2]:
def layer(m1, m2, w1, w2):
    z = m1.dot(w1) + m2.dot(w2) + b

In [39]:
array = np.array([[1,1,1], [2, 2, 2]])

In [4]:
array[[0, 1], [1, 1]] - 1

array([0, 1])

In [12]:
def softmax_grad(softmax):
    s = softmax.reshape(-1,1)
    return np.diagflat(s) - np.dot(s, s.T)

In [13]:
softmax_grad(np.array([[0.5, 0.5]]))

array([[ 0.25, -0.25],
       [-0.25,  0.25]])

In [9]:
(array > 1) * np.array([[1, 1, 1], [1, 1, 1]])

array([[0, 0, 0],
       [1, 1, 1]])

In [40]:
array - 1

array([[0, 0, 0],
       [1, 1, 1]])